import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  FolderOutline,
  FileOutline,
  DownloadOutline,
  HomeOutline,
  FileAddOutline,
  FolderAddOutline,
  DeleteOutline,
  TeamOutline,
  PlusOutline,
  EditOutline,
  KeyOutline,
  FileImageOutline,
  VideoCameraOutline,
  SoundOutline,
  FilePdfOutline,
  FileTextOutline,
  FileZipOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  FolderOutline,
  FileOutline,
  DownloadOutline,
  HomeOutline,
  FileAddOutline,
  FolderAddOutline,
  DeleteOutline,
  TeamOutline,
  PlusOutline,
  EditOutline,
  KeyOutline,
  FileImageOutline,
  VideoCameraOutline,
  SoundOutline,
  FilePdfOutline,
  FileTextOutline,
  FileZipOutline,
];
