import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  FolderOutline,
  FileOutline,
  DownloadOutline,
  HomeOutline,
  FileAddOutline,
  FolderAddOutline,
  DeleteOutline,
  TeamOutline,
  PlusOutline,
  EditOutline,
  KeyOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  FolderOutline,
  FileOutline,
  DownloadOutline,
  HomeOutline,
  FileAddOutline,
  FolderAddOutline,
  DeleteOutline,
  TeamOutline,
  PlusOutline,
  EditOutline,
  KeyOutline,
];
