spring.application.name=anzenfs

spring.threads.virtual.enabled=true

# Max size for a single file
spring.servlet.multipart.max-file-size=500GB
# Max size for the entire request
spring.servlet.multipart.max-request-size=500GB