spring.application.name=anzenfs

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:sqlite:${custom.db.path}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

# Max size for a single file
spring.servlet.multipart.max-file-size=500GB
# Max size for the entire request
spring.servlet.multipart.max-request-size=500GB

app.jwt.secret=fjieaozpnbrzpidsopqgioapzngoeprarhazkmqdpqisvuepzauaefzijeopagrupcdhsqphgezae